import { FreeTierScript } from '../types/freeTier';

/**
 * Generate formatted plain-text / markdown report for a script analysis
 */
export function generateScriptReportText(script: FreeTierScript): string {
  const result = script.analysisResult;
  const dateStr = new Date(script.createdAt).toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const divider = '='.repeat(60);
  const subDivider = '-'.repeat(60);

  let report = `${divider}\n`;
  report += `KONTAGI SCRIPT ANALYSIS REPORT\n`;
  report += `${divider}\n\n`;

  report += `SCRIPT TITLE : ${script.title}\n`;
  report += `CONTENT TYPE : ${script.contentType}\n`;
  report += `ANALYSIS DATE: ${dateStr}\n`;
  report += `WORD COUNT   : ${script.wordCount} words (${script.characterCount || script.scriptText.length} characters)\n`;
  report += `SPEAKING TIME: ~${script.estimatedSpeakingTime || Math.round(script.wordCount * 0.4)} seconds\n\n`;

  report += `${subDivider}\n`;
  report += `1. HOOK SCORE & RETENTION DIAGNOSIS\n`;
  report += `${subDivider}\n`;
  report += `SCORE  : ${script.hookScore} / 100\n`;
  report += `STATUS : ${result?.hookStatus || 'Good Foundation'}\n`;
  report += `SUMMARY: ${result?.hookSupportingText || ''}\n\n`;

  report += `COMPONENT BREAKDOWN:\n`;
  report += `  - Attention / Pattern Interrupt : ${result?.scoreBreakdown?.attention || 0} / 100\n`;
  report += `  - Curiosity & Interest          : ${result?.scoreBreakdown?.interest || 0} / 100\n`;
  report += `  - Specificity & Clarity         : ${result?.scoreBreakdown?.clarity || 0} / 100\n`;
  report += `  - Target Audience Relevance     : ${result?.scoreBreakdown?.relevance || 0} / 100\n`;
  report += `  - Contrarian / Tension Impact   : ${result?.scoreBreakdown?.emotionalImpact || 0} / 100\n\n`;

  if (script.signals && script.signals.length > 0) {
    report += `DETECTED SIGNALS:\n`;
    script.signals.forEach(sig => {
      report += `  [✓] ${sig}\n`;
    });
    report += `\n`;
  }

  report += `${subDivider}\n`;
  report += `2. KEY INSIGHTS & RECOMMENDATIONS\n`;
  report += `${subDivider}\n`;

  if (result?.insights?.positive?.length) {
    report += `STRENGTHS:\n`;
    result.insights.positive.forEach(p => report += `  + ${p}\n`);
    report += `\n`;
  }

  if (result?.insights?.improvement?.length) {
    report += `AREAS FOR IMPROVEMENT:\n`;
    result.insights.improvement.forEach(imp => report += `  ! ${imp}\n`);
    report += `\n`;
  }

  if (result?.suggestions?.length) {
    report += `RECOMMENDATIONS:\n`;
    result.suggestions.forEach((sug, idx) => {
      report += `  ${idx + 1}. ${sug.title}\n`;
      report += `     Explanation: ${sug.explanation}\n`;
      if (sug.example) {
        report += `     Example    : ${sug.example}\n`;
      }
      report += `\n`;
    });
  }

  report += `${subDivider}\n`;
  report += `3. SCRIPT REVIEW BY SECTION\n`;
  report += `${subDivider}\n`;

  if (result?.scriptReview) {
    report += `[HOOK SECTION]\n`;
    report += `  Original Hook: "${result.scriptReview.hook?.text || script.hookText}"\n`;
    report += `  What Works   : ${result.scriptReview.hook?.works || ''}\n`;
    report += `  To Improve   : ${result.scriptReview.hook?.improve || ''}\n`;
    if (result.scriptReview.hook?.rewrite) {
      report += `  AI Rewrite   : "${result.scriptReview.hook.rewrite}"\n`;
    }
    report += `\n`;

    report += `[BODY SECTION]\n`;
    report += `  What Works   : ${result.scriptReview.body?.works || ''}\n`;
    report += `  To Improve   : ${result.scriptReview.body?.improve || ''}\n\n`;

    report += `[CALL TO ACTION]\n`;
    report += `  CTA Text     : "${result.scriptReview.cta?.text || ''}"\n`;
    report += `  What Works   : ${result.scriptReview.cta?.works || ''}\n`;
    report += `  To Improve   : ${result.scriptReview.cta?.improve || ''}\n\n`;
  }

  report += `${subDivider}\n`;
  report += `4. COMPLETE SCRIPT TEXT\n`;
  report += `${subDivider}\n`;
  report += `${script.scriptText}\n\n`;

  report += `${divider}\n`;
  report += `Generated by KONTAGI Script Intelligence • ${new Date().toISOString()}\n`;
  report += `${divider}\n`;

  return report;
}

/**
 * Trigger browser file download of the script analysis report
 */
export function downloadScriptReport(script: FreeTierScript): void {
  const content = generateScriptReportText(script);
  const cleanTitle = (script.title || 'Script_Analysis').toLowerCase().replace(/[^a-z0-9]/g, '_').substring(0, 30);
  const filename = `KONTAGI_Report_${cleanTitle}.txt`;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Trigger browser file download of pure script text
 */
export function downloadScriptText(text: string, title?: string): void {
  const cleanTitle = (title || 'Script').toLowerCase().replace(/[^a-z0-9]/g, '_').substring(0, 30);
  const filename = `KONTAGI_${cleanTitle}.txt`;

  const blob = new Blob([text], { type: 'text/plain;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
